### ISSUE TITLE
can you give an example of the config options in umirc.js?

### ISSUE THREAD

**Issue by chj-damon** [lemol/umi-plugin-apollo#1]
Thank you for creating this wonderful repository, I want to use it in my project but I got some problems with the configuration. I was wondering if you can share an example that how I can config apollo in .umirc.js.
I checked out the source code, But I'm really confused by 'template/umi/apollo/pageResolvers.js' this file. I want to try https://hackernoon.com/setting-up-apollo-link-state-for-multiple-stores-4cf54fdb1e00 this way.
Can you give me any advice about it?
Thanks so much for your help.

**Comment by lemol** [comment]
@chj-damon , I'm sorry for the delay responding here.
I just updated the repository with some examples of use. You can check source code here https://github.com/lemol/umi-plugin-apollo/tree/master/examples/basic . This example shows how to use either remote queries or client state.

Please, let me know if it may fit to your use case.

**Comment by chj-damon** [comment]
Thank you so much!
