### ISSUE TITLE
Support for Apollo Link REST

### ISSUE THREAD

**Issue by nicostuhlfauth** [lemol/umi-plugin-apollo#12]
Does this plugin support [`apollo-link-rest`](https://www.apollographql.com/docs/link/links/rest)? If yes, could you please add a guide that describes how to get it running?

**Comment by lemol** [comment]
@nicostuhlfauth I just add an example of using `apollo-link-rest`. You can find the needed changes in this commit diff 647b1c60e2a26f81b8cb23a247c5a972023c6222.

Basically, any customization to can be done creating the `options` file. In this case the solution was to add the following to the `options` file:

```javascript
import { RestLink } from "apollo-link-rest";

const restLink = new RestLink({
  uri: 'https://swapi.co/api/',
});

export const extraLinks = [
  restLink,
];
```

**Comment by nicostuhlfauth** [comment]
Thanks 😄
