### ISSUE TITLE
How to get apollo client?

### ISSUE THREAD

**Issue by zven21** [lemol/umi-plugin-apollo#14]
HI, I would like to know how to get `apollo client`?

because `<Query /> ` cannot meet all my scenes.  so i try to use 

```javascript
client.query({
   query: G.XXX,
   variables: { term: { } },
}).then()
```
Thanks. :smile:

**Comment by wanxger** [comment]
https://www.apollographql.com/docs/react/essentials/queries/#manually-firing-a-query

**Comment by zven21** [comment]
thank you.
