### ISSUE TITLE
how we can use dvajs as state manager with umi-plugin-apollo?

### ISSUE THREAD

**Issue by rmros** [lemol/umi-plugin-apollo#15]
@lemol 
i have apollo graphql server already ,
 antd-dashboard-pro is developed  dva and umijs base
i want use dvajs as built-in state management for my project
how i can integrate these together with umi-plugin-apollo ?

**Comment by lemol** [comment]
Hi @rmros ,

I find this example trying to integrate apollo-graphql with dva https://github.com/codejie/dva-graphql-mqtt-demo.

What do you think?

**Comment by rmros** [comment]
hi @lemol meaning i cant use umi-plugin-apollo for this job? how i can use https://github.com/codejie/dva-graphql-mqtt-demo to integrate with antd-dashboard pro?

**Comment by agustif** [comment]
You could certainly use it, take the mqtt example as only that, an example, and do your own implementation. You could also scrap dvajs altogether and use whatever you want to manage your state, dva, redux directly, mobx, or whatever is cool this days anyway!

@lemol Thanks for umi-plugin-apollo, working perfectly for my graphql-modules/apollo-server backend + ant.design.pro frontend
