### ISSUE TITLE
the graphql loader issue not fixed in latest npm version

### ISSUE THREAD

**Issue by xxx-adi** [lemol/umi-plugin-apollo#18]
this graphql loader issue seems to be fixed in the latest commit , but the version is not bumped yet. so the plugin installed through npm is still the buggy version 0.0.17 @lemol

_Originally posted by @xxx-adi in https://github.com/lemol/umi-plugin-apollo/issues/16#issuecomment-568699453_

**Comment by lemol** [comment]
Thank you @xxx-adi .
Just published the latest version to npm.
