### ISSUE TITLE
Authentication/Authorization

### ISSUE THREAD

**Issue by imcvampire** [lemol/umi-plugin-apollo#2]
How can I set header `Authorization` after user logins to apollo client

**Comment by lemol** [comment]
@imcvampire  this is not documented yet, but I'm working to improve the docs for this by tomorrow.

You can add a `src/options/apollo.js` file in where you can setup your `ApolloClient`.

Following is an example for the `src/options/apollo.js` file:

```js
import { setContext } from 'apollo-link-context';
import { getAuthToken } from '@/utils/auth';

const authLink = setContext(async (_, { headers }) => {
  const token = await getAuthToken();
  const authorizationHeader = token
    ? { authorization: `Bearer ${token}` }
    : {};

  return {
    headers: {
      ...headers,
      ...authorizationHeader,
    },
  };
});

export const extraLinks = [
  authLink,
];
```

This https://github.com/lemol/angolans-on-github/tree/master/packages/react-umi-apollo project is an example also.

Makes sense for your use case?

**Comment by imcvampire** [comment]
I can set it programmatically, am I? My use case is using restful API to get token from a server, then save it to cookie and update header to graphql client too

**Comment by lemol** [comment]
In this https://github.com/lemol/angolans-on-github/blob/master/packages/react-umi-apollo example a github token is provided using `firebase auth`, and saved on LocalStorage, then in `src/options/apollo.js` is configured to set the graphql calls with the token retrieved from LocalStorage.

You can check the live example here: https://angolans-on-github.now.sh

**Comment by imcvampire** [comment]
Thank you
