### ISSUE TITLE
Error: umi generate apollo:page does not work when config.routes exists

### ISSUE THREAD

**Issue by rmros** [lemol/umi-plugin-apollo#5]
1) `npm create umi`
i selected ant-design-pro 
2) inside ant design pro folder i add umi-plugin-apollo  and then i add into config.js file
3) and  i enter ` umi generate apollo:page user/index`

i get this error 
Error: umi generate apollo:page does not work when config.routes exists

i tried several times to run that but lose
also i add this to umi-plugin-react route
```
        exclude: [
          /schema\.(js|jsx|ts|tsx)$/,
          /resolvers\.(js|jsx|ts|tsx)$/,
        ],
```

**Comment by lemol** [comment]
@rmros, thank you again. Just fixed it.
