### ISSUE TITLE
Umi plugin for apollo graphql client with hooks support.

### ISSUE THREAD

**Issue by rmros** [lemol/umi-plugin-apollo#6]
your forked repository added react hooks support feature in your umi-plugin-apollo
i think its good idea you add this feature in main project

**Comment by lemol** [comment]
@rmros, I'm strongly interested in adding react-apollo-hooks support.

I checked the tuofeng-inc/umi-plugin-apollo fork, and I would ask if @tuofeng-inc (@iwater) want to merge back their great work. I will quickly merge a pull request.
