### ISSUE TITLE
there are some errors here, please see the pic

### ISSUE THREAD

**Issue by rmros** [lemol/umi-plugin-apollo#8]
![screenshot 2019-03-03 19 57 32](https://user-images.githubusercontent.com/21344663/53698177-622ae580-3dee-11e9-9b2b-6be7eac169a6.png)

**Comment by rmros** [comment]
@lemol  its happened when 
1) npm create umi
select app
2) umi generate apollo:page user/index
3) browsed http://localhost:8000/user  and saw these errors

thanks

**Comment by lemol** [comment]
@rmros thank you for your excellent job.
I was not testing for typescript but now will have more attention on it.
Just published a fix.

**Comment by rmros** [comment]
@lemol im thank you too for your great job,
